Repository leekahhow/rails-airbnb-clone, pull requests merged in 2020-06, with the labels that each got.

#17 resolved linking form with DB
  app/controllers/application_controller.rb
  app/models/region.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/layouts/application.html.erb
Labels: enhancement

#19 Fix deployment
  RUBY_VERSION
  app/models/booking.rb
Labels: bug

#42 Cloundinary heroku production
  Gemfile
  Gemfile.lock
  app/controllers/bookings_controller.rb
  app/controllers/pets_controller.rb
  app/models/booking.rb
  app/models/pet.rb
  app/models/user.rb
  app/views/bookings/new.html.erb
  app/views/pets/new.html.erb
  app/views/pets/show.html.erb
  app/views/shared/_navbar.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  config/storage.yml
  db/migrate/20200606001146_create_active_storage_tables.active_storage.rb
  db/migrate/20200606002753_add_photo_to_pets_table.rb
  db/migrate/20200606051306_remove_photo_field_from_pets_table.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#41 resolved seed issue, added cloudinary form and active storage but ima…
  Gemfile
  Gemfile.lock
  app/controllers/pets_controller.rb
  app/models/booking.rb
  app/models/pet.rb
  app/models/user.rb
  app/views/pets/new.html.erb
  app/views/pets/show.html.erb
  app/views/shared/_navbar.html.erb
  config/environments/development.rb
  config/storage.yml
  db/migrate/20200606001146_create_active_storage_tables.active_storage.rb
  db/migrate/20200606002753_add_photo_to_pets_table.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#48 Navbar homepage text
  app/views/bookings/index.html.erb
  app/views/bookings/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/pets/index.html.erb
  app/views/pets/new.html.erb
  app/views/pets/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: enhancement

#53 Create review system
  app/controllers/bookings_controller.rb
  app/controllers/reviews_controller.rb
  app/views/bookings/_booking.html.erb
  app/views/bookings/index.html.erb
  app/views/bookings/show.html.erb
  app/views/pets/show.html.erb
  app/views/reviews/create.html.erb
  app/views/reviews/new.html.erb
  config/routes.rb
Labels: enhancement

#61 Create review system
  app/controllers/reviews_controller.rb
  app/models/pet.rb
  app/models/review.rb
  app/views/bookings/_booking.html.erb
  app/views/pets/show.html.erb
  app/views/reviews/new.html.erb
  app/views/shared/_navbar.html.erb
Labels: bug, enhancement

#77 Homepage styling improvement
  app/assets/stylesheets/components/_home.scss
  app/assets/stylesheets/components/_index.scss
  app/controllers/application_controller.rb
  app/controllers/bookings_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/reviews_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/bookings/index.html.erb
  app/views/bookings/show.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/pets/_pet.html.erb
  app/views/pets/show.html.erb
  app/views/reviews/_form.html.erb
  app/views/reviews/_review.html.erb
  app/views/reviews/new.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  test/controllers/users_controller_test.rb
Labels: enhancement

#85 fixed seeds
  app/assets/stylesheets/components/_navbar.scss
  app/views/bookings/_booking.html.erb
  app/views/bookings/_mypet.html.erb
  app/views/pets/_pet.html.erb
  app/views/pets/show.html.erb
  db/images/pet1.jpg
  db/images/pet10.jpg
  db/images/pet11.jpg
  db/images/pet12.jpg
  db/images/pet13.jpg
  db/images/pet14.jpg
  db/images/pet15.jpg
  db/images/pet16.jpg
  db/images/pet17.jpg
  db/images/pet18.jpg
  db/images/pet2.jpg
  db/images/pet3.jpg
  db/images/pet4.jpg
  db/images/pet5.jpg
  db/images/pet6.jpg
  db/images/pet7.jpg
  db/images/pet8.jpg
  db/images/pet9.jpg
  db/seeds.rb
Labels: Essential Feature, enhancement

#87 If else
  app/controllers/pets_controller.rb
  app/controllers/users_controller.rb
  app/views/bookings/_mypet.html.erb
  app/views/pets/show.html.erb
  app/views/users/show.html.erb
Labels: enhancement

#88 If else users show
  app/controllers/users_controller.rb
  app/views/users/show.html.erb
Labels: bug

#90 resolved if else
  app/controllers/pets_controller.rb
  app/controllers/users_controller.rb
  app/views/pets/show.html.erb
  app/views/users/show.html.erb
  db/migrate/20200612132500_change_default_booking_state.rb
  db/schema.rb
Labels: enhancement

#93 Styling forms
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/pets/index.html.erb
  app/views/users/show.html.erb
  db/images/vector/login_vector.png
  db/images/vector/pets_vector.png
  db/images/vector/signup_vector.png
Labels: Essential Feature, enhancement

#94 Navbarimage
  app/views/shared/_navbar.html.erb
  db/images/jh.png
  db/images/jn.png
  db/images/kh.png
  db/images/sam.png
  db/seeds.rb
Labels: enhancement

#100 Filter icons category
  app/assets/stylesheets/components/_filter_category.scss
  app/assets/stylesheets/components/_index.scss
  app/controllers/pets_controller.rb
  app/views/pets/index.html.erb
  app/views/shared/_filter_category.html.erb
Labels: enhancement
